name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Detecta cambios en la rama 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Render
        env:
          RENDER_API_TOKEN: ${{ secrets.RENDER_API_TOKEN }}
        run: |
          curl -X POST \
          -H "Authorization: Bearer $RENDER_API_TOKEN" \
          -d '{"serviceId": "<ID_DEL_SERVICIO>"}' \
          https://api.render.com/v1/services/<ID_DEL_SERVICIO>/deploys


# name: CI/CD Pipeline for Render

# on:
#   push:
#     branches:
#       - main  # O la rama que quieras monitorizar para despliegue
#   pull_request:
#     branches:
#       - main  # Si quieres desplegar también con PR

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Set up Docker
#       uses: docker/setup-buildx-action@v1

#     - name: Build Docker image
#       run: |
#         docker build -t my-app .
        
#     - name: Login to Render
#       run: |
#         echo "Logging in to Render"
#         curl -fsSL https://render.com/deploy.json | jq -r .token | docker login --username render --password-stdin
        
#     - name: Push Docker image to Render
#       run: |
#         docker tag my-app render.com/my-app:latest
#         docker push render.com/my-app:latest
        
#     - name: Deploy to Render
#       run: |
#         curl -X POST https://api.render.com/deploys -d '{"serviceId": "5b2da32"}' -H "Authorization: Bearer YOUR_RENDER_API_KEY"

